[project]
name = "codygo-dep1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dani Kenan", email = "danikenan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "codygo-dep2",
]

# [project.scripts]
# codygo-dep1 = "codygo_dep1:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
codygo-dep2 = { workspace = true }
